# Generated by Django 4.2.1 on 2023-06-04 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0002_remove_position_related_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='related_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visual.contract'),
        ),
    ]
