# Generated by Django 4.2.1 on 2023-06-05 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0004_contract_created_at_creditapplication_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='created_at',
        ),
    ]
